apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  path: ./flux/staging
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  interval: 1m0s
  serviceAccountName: instavote
  prune: false
