apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  prune: true  # you're overriding this
  interval: 5m0s  # or any field you're patching

